import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/widgets.dart'
    as pw;
import 'package:printing/printing.dart';

import '../../../models/payment_model.dart';

class PaymentReceiptScreen
    extends StatelessWidget {
  final PaymentModel payment;

  const PaymentReceiptScreen({
    super.key,
    required this.payment,
  });

  //--------------------------------------------------
  // PRINT RECEIPT
  //--------------------------------------------------

  Future<void> _printReceipt() async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (context) {
          return pw.Column(
            crossAxisAlignment:
                pw.CrossAxisAlignment.start,
            children: [

              pw.Text(
                "SMART EMPLOYEE TRAVEL SYSTEM",
                style: pw.TextStyle(
                  fontSize: 22,
                  fontWeight:
                      pw.FontWeight.bold,
                ),
              ),

              pw.SizedBox(height: 8),

              pw.Text(
                "PAYMENT RECEIPT",
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight:
                      pw.FontWeight.bold,
                ),
              ),

              pw.Divider(),

              pw.Text(
                "Invoice No : ${payment.invoiceNumber}",
              ),

              pw.Text(
                "Transaction ID : ${payment.transactionId}",
              ),

              pw.Text(
                "Payment ID : ${payment.paymentId}",
              ),

              pw.Text(
                "Trip ID : ${payment.tripId}",
              ),

              pw.Text(
                "Employee : ${payment.employeeName}",
              ),

              pw.Text(
                "Payment Method : ${payment.paymentMethod}",
              ),

              pw.Text(
                "Payment Status : ${payment.paymentStatus}",
              ),

              pw.Text(
                "Amount : ₹${payment.amount.toStringAsFixed(2)}",
              ),

              pw.Text(
                "GST : ₹${payment.gst.toStringAsFixed(2)}",
              ),

              pw.Text(
                "Total : ₹${payment.totalAmount.toStringAsFixed(2)}",
              ),

              pw.SizedBox(height: 15),

              pw.Text(
                "Payment Date : ${DateFormat("dd MMM yyyy, hh:mm a").format(payment.paymentDate)}",
              ),

              if (payment
                  .remarks
                  .isNotEmpty)
                pw.Text(
                  "Remarks : ${payment.remarks}",
                ),

              pw.Spacer(),

              pw.Divider(),

              pw.Center(
                child: pw.Text(
                  "Generated by Smart Employee Travel System",
                ),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (_) async =>
          pdf.save(),
    );
  }

  @override
  Widget build(
    BuildContext context,
  ) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          "Payment Receipt",
        ),
        centerTitle: true,
        actions: [

          IconButton(
            icon: const Icon(
              Icons.picture_as_pdf,
            ),
            onPressed:
                _printReceipt,
          ),

        ],
      ),

      body: SingleChildScrollView(
        padding:
            const EdgeInsets.all(16),

        child: Card(
          elevation: 4,
          child: Padding(
            padding:
                const EdgeInsets.all(20),

            child: Column(
              children: [
                                //--------------------------------------------------
                // RECEIPT HEADER
                //--------------------------------------------------

                const Icon(
                  Icons.check_circle,
                  color: Colors.green,
                  size: 80,
                ),

                const SizedBox(height: 12),

                const Text(
                  "Payment Successful",
                  style: TextStyle(
                    fontSize: 22,
                    fontWeight:
                        FontWeight.bold,
                  ),
                ),

                const SizedBox(height: 6),

                Text(
                  payment.paymentStatus,
                  style: TextStyle(
                    fontSize: 16,
                    color:
                        payment.paymentStatus ==
                                "Paid"
                            ? Colors.green
                            : Colors.orange,
                    fontWeight:
                        FontWeight.w600,
                  ),
                ),

                const Divider(
                  height: 35,
                ),

                //--------------------------------------------------
                // RECEIPT DETAILS
                //--------------------------------------------------

                _row(
                  "Invoice No",
                  payment.invoiceNumber,
                ),

                _row(
                  "Transaction ID",
                  payment.transactionId,
                ),

                _row(
                  "Payment ID",
                  payment.paymentId,
                ),

                _row(
                  "Trip ID",
                  payment.tripId,
                ),

                _row(
                  "Employee",
                  payment.employeeName,
                ),

                _row(
                  "Payment Method",
                  payment.paymentMethod,
                ),

                _row(
                  "Payment Status",
                  payment.paymentStatus,
                ),

                _row(
                  "Amount",
                  "₹${payment.amount.toStringAsFixed(2)}",
                ),

                _row(
                  "GST",
                  "₹${payment.gst.toStringAsFixed(2)}",
                ),

                _row(
                  "Total Amount",
                  "₹${payment.totalAmount.toStringAsFixed(2)}",
                ),

                _row(
                  "Payment Date",
                  DateFormat(
                    "dd MMM yyyy, hh:mm a",
                  ).format(
                    payment.paymentDate,
                  ),
                ),

                if (payment
                    .remarks
                    .isNotEmpty)
                  _row(
                    "Remarks",
                    payment.remarks,
                  ),

                const SizedBox(
                  height: 25,
                ),
                                //--------------------------------------------------
                // ACTION BUTTONS
                //--------------------------------------------------

                SizedBox(
                  width: double.infinity,
                  height: 55,
                  child: ElevatedButton.icon(
                    onPressed: _printReceipt,
                    icon: const Icon(
                      Icons.print,
                    ),
                    label: const Text(
                      "Print Receipt",
                    ),
                  ),
                ),

                const SizedBox(
                  height: 12,
                ),

                SizedBox(
                  width: double.infinity,
                  height: 55,
                  child: OutlinedButton.icon(
                    onPressed: () {
                      Navigator.pop(
                        context,
                      );
                    },
                    icon: const Icon(
                      Icons.arrow_back,
                    ),
                    label: const Text(
                      "Back",
                    ),
                  ),
                ),

                const SizedBox(
                  height: 10,
                ),

              ],
            ),
          ),
        ),
      ),
    );
  }

  //--------------------------------------------------
  // RECEIPT ROW
  //--------------------------------------------------

  Widget _row(
    String title,
    String value,
  ) {
    return Padding(
      padding:
          const EdgeInsets.symmetric(
        vertical: 6,
      ),
      child: Row(
        crossAxisAlignment:
            CrossAxisAlignment.start,
        children: [

          Expanded(
            flex: 2,
            child: Text(
              title,
              style: const TextStyle(
                fontWeight:
                    FontWeight.w600,
              ),
            ),
          ),

          const Text(" : "),

          Expanded(
            flex: 3,
            child: Text(
              value,
              textAlign:
                  TextAlign.end,
            ),
          ),

        ],
      ),
    );
  }
}