import 'dart:io';

import 'package:excel/excel.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

class ExcelReport {
  ExcelReport._();

  static Future<File> generate({
    required int employees,
    required int drivers,
    required int vehicles,
    required int trips,
    required int pending,
    required int assigned,
    required int started,
    required int completed,
    required int cancelled,
  }) async {
    final excel = Excel.createExcel();

    final Sheet sheet = excel['Smart Employee Travel Report'];

    excel.delete('Sheet1');

    final generatedOn = DateFormat(
      'dd MMM yyyy  hh:mm a',
    ).format(DateTime.now());

    sheet.appendRow([
      TextCellValue('SMART EMPLOYEE TRAVEL SOLUTION'),
    ]);

    sheet.appendRow([
      TextCellValue(
        'Smart Employee Travel Management System',
      ),
    ]);

    sheet.appendRow([]);

    sheet.appendRow([
      TextCellValue('Generated On'),
      TextCellValue(generatedOn),
    ]);

    sheet.appendRow([]);

    sheet.appendRow([
      TextCellValue('DASHBOARD SUMMARY'),
    ]);

    sheet.appendRow([
      TextCellValue('Category'),
      TextCellValue('Count'),
    ]);
        //==================================================
    // Dashboard Summary
    //==================================================

    sheet.appendRow([
      TextCellValue('Employees'),
      IntCellValue(employees),
    ]);

    sheet.appendRow([
      TextCellValue('Drivers'),
      IntCellValue(drivers),
    ]);

    sheet.appendRow([
      TextCellValue('Vehicles'),
      IntCellValue(vehicles),
    ]);

    sheet.appendRow([
      TextCellValue('Trips'),
      IntCellValue(trips),
    ]);

    sheet.appendRow([]);

    //==================================================
    // Trip Status Report
    //==================================================

    sheet.appendRow([
      TextCellValue('TRIP STATUS REPORT'),
    ]);

    sheet.appendRow([
      TextCellValue('Status'),
      TextCellValue('Count'),
    ]);

    sheet.appendRow([
      TextCellValue('Pending'),
      IntCellValue(pending),
    ]);

    sheet.appendRow([
      TextCellValue('Assigned'),
      IntCellValue(assigned),
    ]);

    sheet.appendRow([
      TextCellValue('Started'),
      IntCellValue(started),
    ]);

    sheet.appendRow([
      TextCellValue('Completed'),
      IntCellValue(completed),
    ]);

    sheet.appendRow([
      TextCellValue('Cancelled'),
      IntCellValue(cancelled),
    ]);

    sheet.appendRow([]);

    //==================================================
    // Completion Percentage
    //==================================================

    final completion =
        trips == 0
            ? 0.0
            : (completed / trips) * 100;

    sheet.appendRow([
      TextCellValue('Trip Completion'),
      TextCellValue(
        '${completion.toStringAsFixed(2)} %',
      ),
    ]);

    sheet.appendRow([]);

    sheet.appendRow([
      TextCellValue(
        'Generated By : Smart Employee Travel Solution',
      ),
    ]);
        //==================================================
    // Save Excel File
    //==================================================

    final directory =
        await getApplicationDocumentsDirectory();

    final file = File(
      '${directory.path}/Smart_Employee_Travel_System_Report.xlsx',
    );

    final bytes = excel.encode();

    if (bytes == null) {
      throw Exception(
        'Failed to generate Excel file.',
      );
    }

    await file.writeAsBytes(bytes);

    return file;
  }

  //==================================================
  // Share Excel Report
  //==================================================

  static Future<void> shareReport(
    File file,
  ) async {
    await Share.shareXFiles(
      [
        XFile(file.path),
      ],
      subject: 'Smart Employee Travel Solution Report',
      text:
          'Please find the attached Smart Employee Travel Solution Excel Report.',
    );
  }

  //==================================================
  // Generate & Share
  //==================================================

  static Future<void> generateAndShare({
    required int employees,
    required int drivers,
    required int vehicles,
    required int trips,
    required int pending,
    required int assigned,
    required int started,
    required int completed,
    required int cancelled,
  }) async {
    final file = await generate(
      employees: employees,
      drivers: drivers,
      vehicles: vehicles,
      trips: trips,
      pending: pending,
      assigned: assigned,
      started: started,
      completed: completed,
      cancelled: cancelled,
    );

    await shareReport(file);
  }
}