import 'dart:io';

import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

class PdfReport {
  PdfReport._();

  static Future<File> generate({
    required int employees,
    required int drivers,
    required int vehicles,
    required int trips,
    required int pending,
    required int assigned,
    required int started,
    required int completed,
    required int cancelled,
  }) async {
    final pdf = pw.Document();

    final generatedOn = DateFormat(
      'dd MMM yyyy  hh:mm a',
    ).format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,

        margin: const pw.EdgeInsets.all(24),

        build: (context) {
          return [

            pw.Center(
              child: pw.Column(
                children: [

                  pw.Text(
                    "SMART EMPLOYEE TRAVEL SOLUTION",
                    style: pw.TextStyle(
                      fontSize: 24,
                      fontWeight:
                          pw.FontWeight.bold,
                    ),
                  ),

                  pw.SizedBox(height: 5),

                  pw.Text(
                    "Smart Employee Travel Management System",
                  ),

                  pw.SizedBox(height: 10),

                  pw.Text(
                    "Generated On : $generatedOn",
                  ),

                ],
              ),
            ),

            pw.SizedBox(height: 30),

            pw.Text(
              "Dashboard Summary",
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight:
                    pw.FontWeight.bold,
              ),
            ),

            pw.SizedBox(height: 10),
                        pw.TableHelper.fromTextArray(
              border: pw.TableBorder.all(
                color: PdfColors.grey700,
              ),
              headerDecoration: const pw.BoxDecoration(
                color: PdfColors.blueGrey,
              ),
              headerStyle: pw.TextStyle(
                color: PdfColors.white,
                fontWeight: pw.FontWeight.bold,
              ),
              headers: const [
                'Category',
                'Count',
              ],
              data: [
                ['Employees', employees.toString()],
                ['Drivers', drivers.toString()],
                ['Vehicles', vehicles.toString()],
                ['Trips', trips.toString()],
              ],
            ),

            pw.SizedBox(height: 25),

            pw.Text(
              "Trip Status Report",
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
              ),
            ),

            pw.SizedBox(height: 10),

            pw.TableHelper.fromTextArray(
              border: pw.TableBorder.all(
                color: PdfColors.grey700,
              ),
              headerDecoration: const pw.BoxDecoration(
                color: PdfColors.green,
              ),
              headerStyle: pw.TextStyle(
                color: PdfColors.white,
                fontWeight: pw.FontWeight.bold,
              ),
              headers: const [
                'Status',
                'Count',
              ],
              data: [
                ['Pending', pending.toString()],
                ['Assigned', assigned.toString()],
                ['Started', started.toString()],
                ['Completed', completed.toString()],
                ['Cancelled', cancelled.toString()],
              ],
            ),

            pw.SizedBox(height: 25),

            pw.Text(
              "Trip Completion",
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
              ),
            ),

            pw.SizedBox(height: 10),

            pw.Text(
              trips == 0
                  ? "0 %"
                  : "${((completed / trips) * 100).toStringAsFixed(2)} %",
              style: pw.TextStyle(
                fontSize: 16,
                color: PdfColors.green800,
                fontWeight: pw.FontWeight.bold,
              ),
            ),

            pw.SizedBox(height: 30),

            pw.Divider(),

            pw.Center(
              child: pw.Text(
                "Generated by Smart Employee Travel Solution",
                style: const pw.TextStyle(
                  fontSize: 10,
                ),
              ),
            ),
                      ];
        },
      ),
    );

    final directory =
        await getApplicationDocumentsDirectory();

    final file = File(
      '${directory.path}/Smart_Employee_Travel_System_Report.pdf',
    );

    await file.writeAsBytes(
      await pdf.save(),
    );

    return file;
  }

  //==================================================
  // Share PDF Report
  //==================================================

  static Future<void> shareReport(
    File file,
  ) async {
    await Share.shareXFiles(
      [
        XFile(file.path),
      ],
      subject: 'Smart Employee Travel Solution PDF Report',
      text:
          'Please find the attached Smart Employee Travel Solution PDF Report.',
    );
  }

  //==================================================
  // Generate & Share PDF
  //==================================================

  static Future<void> generateAndShare({
    required int employees,
    required int drivers,
    required int vehicles,
    required int trips,
    required int pending,
    required int assigned,
    required int started,
    required int completed,
    required int cancelled,
  }) async {
    final file = await generate(
      employees: employees,
      drivers: drivers,
      vehicles: vehicles,
      trips: trips,
      pending: pending,
      assigned: assigned,
      started: started,
      completed: completed,
      cancelled: cancelled,
    );

    await shareReport(file);
  }
}